### ISSUE TITLE
Glitched Selection

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#140]
Submitter: ProtoMegaMan147
Email: ackminer@gmail.com
For some reason, when I try to select and object or a tile set, the selection with flicker on and off. As a result, I can no longer choose a tile set or and object. I say no longer as when I first started out, I was able to choose tile sets and objects just fine.

**Comment by snoruntpyro** [comment]
For an answer to your problem, please refer to the blatant note about it in the release thread. Alternatively, refer to the first pinned message in the #engine-discussion channel. Alternatively alternatively, scroll up in the #engine-announcements channel and find a message specifically explaining this. Alternatively alternatively alternatively, look in the same channel (or search the forums) and find ACE's first tutorial video which is unlisted for now due to the engine not being open yet but is still around for you to watch, where he explains this issue within the first few minutes. Alternatively alternatively alternatively alternatively, look in #engine-discussion's history and gaze at the seventeen million people who have asked this question before and got very exasperated responses because people don't actually read anything we post about the flickering issue.

If you didn't read any of that, the sprites aren't loaded yet please be patient for like 10 minutes before reporting this stupid Studio quirk as a "bug".
