### ISSUE TITLE
1Ups don't properly change for the player's costume

### ISSUE THREAD

**Issue by lnUniverse** [MegamixEngine/MegamixEngine#224]
1Ups are supposed to look like the head of the costume you are currently using, but are instead always the head of Megaman. Oddly, the Camouflametall does properly display the current costume's head.

**Comment by RPGHacker** [comment]
I'd like to report this bug as well. I've looked into the code of objLive and it seems to be a simple bug in the draw event.

```
    if ((flashTimer mod 4) &lt; 2)
    {
        if (object_index == objLife)
        {
            var _costume = 0;
            var _pid = floor((timer / 48) mod global.playerCount);
            with (objMegaman)
            {
                if (playerID == _pid)
                {
                    _pid = playerID;
                    _costume = costumeID;
                    break;
                }
            }
            
            drawPlayer(_pid, _pid, 16, 12, x + 8, y, image_xscale, image_yscale);
        }
}
```

It properly writes the costume ide into `_costume`, but then doesn't pass it to `drawPlayer()` and instead passes `_pid` twice, making the rendered costume dependent on the player's index rather than their selected costume. Since the index of player 1 is always 0, it will always use Mega Man's costume (which also has the index 0) rather than the currently selected costume.

The fix should be as simple as replacing the second `_pid` by `_costume`. I would do a pull request for this, but currently my workspace is too messy, so I hope someone else can do that.

**Comment by snoruntpyro** [comment]
Fixed on dev branch.
