### ISSUE TITLE
Broken GMFMOD

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#417]
Submitter: Raptarr8
Email: raptarreight@gmail.com
Whenever I try to run megamix engine, I get this error:
Error defining an external function.
 at gml_Script_LoadFMOD (line 696) - global.dll_FMODSoundAddAsyncStream = external_define("GMFMODSimple.dll", ############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_LoadFMOD (line 696)
called from - gml_Object_objMusicControl_CreateEvent_1 (line 2) - LoadFMOD(); called from - gml_Object_objGlobalControl_CreateEvent_1 (line 62) - instance_create(0, 0, objMusicControl); 
LoadLibraryA failed with error code 126
This happens all versions, and I have tried reinstalling, but this still happens.
Note: this may be an issue with my computer, I have not tested it on any other device

**Comment by ginger-mochi** [comment]
Error code 126 for [LoadLibraryA](https://docs.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-loadlibrarya) is `ERROR_MOD_NOT_FOUND`, which to me suggests that it can't find the DLL. I'm not very familiar with WinAPI error codes, but it could also be unable to find fmodex.dll, which GMFMODSimple.dll relies on. However, fmodex.dll is included in the repo, so that doesn't seem very likely.

I would suggest clearing your asset cache (use the broom icon in the GMS toolbar) and recompile the project. If that still doesn't work, try adding `GMFMODSimple.dll` and `fmodex.dll` (which are in the `datafiles/` folder) to [your system's PATH](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537574(v=office.14)).

I'm closing this as no-repro for now, as I don't think anyone else has gotten this error.
